"""Prepare a recording-disjoint ECG/PLETH sensor-fault study from training.zip.

The public clinical alarm labels are retained only as metadata. All cyber/sensor
fault labels are assigned to controlled injections generated by this script.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
from pathlib import Path
from zipfile import ZipFile

import numpy as np
import pandas as pd
from scipy.io import loadmat
from sklearn.model_selection import train_test_split

ECG_NAMES = ("II", "I", "III", "V", "MCL", "aVF", "aVL", "aVR")
FAULTS = ("none", "flatline", "dropout", "gain", "replay")


def stats(ecg: np.ndarray, pleth: np.ndarray) -> dict[str, float]:
    # Bounded, comparable features; no recording identity or clinical labels.
    e, p = np.clip(ecg, -20, 20), np.clip(pleth, -20, 20)
    def channel(x: np.ndarray, prefix: str) -> dict[str, float]:
        d = np.diff(x)
        return {f"{prefix}_median": float(np.median(x)),
                f"{prefix}_std": float(np.std(x)),
                f"{prefix}_iqr": float(np.percentile(x, 75) - np.percentile(x, 25)),
                f"{prefix}_diff_std": float(np.std(d)),
                f"{prefix}_flat_fraction": float(np.mean(np.abs(d) < 1e-8)),
                f"{prefix}_missing_fraction": float(np.mean(~np.isfinite(x)))}
    result = channel(e, "ecg") | channel(p, "pleth")
    result["pleth_ecg_diff_std_ratio"] = float(result["pleth_diff_std"] / max(result["ecg_diff_std"], 1e-6))
    return result


def inject(pleth: np.ndarray, fault: str, earlier: np.ndarray) -> np.ndarray:
    altered = pleth.copy()
    if fault == "flatline":
        altered[:] = np.median(pleth)
    elif fault == "dropout":
        altered[len(altered)//4:3*len(altered)//4] = np.nan
    elif fault == "gain":
        altered = 3 * (pleth - np.median(pleth)) + np.median(pleth)
    elif fault == "replay":
        altered = earlier.copy()
    return altered


def history_reference(history: list[np.ndarray]) -> tuple[np.ndarray, np.ndarray]:
    bank = np.stack([np.roll(prior, lag)[::5] for prior in history for lag in range(-5, 6)])
    scales = np.repeat([max(float(np.std(prior)), .01) for prior in history], 11)
    return bank, scales


def robust_history_error(observed: np.ndarray, reference: tuple[np.ndarray, np.ndarray]) -> float:
    """Normalized waveform distance over stored history at offsets -5..5."""
    if not np.isfinite(observed).all():
        return 1e6
    bank, scales = reference
    return float(np.min(np.mean(np.abs(bank - observed[::5]), axis=1) / scales))


def decode(archive: ZipFile, record: str) -> tuple[np.ndarray, np.ndarray, int]:
    header = archive.read(f"training/{record}.hea").decode().splitlines()
    first = header[0].split()
    rate, length = int(first[2]), int(first[3])
    lines = [line.split() for line in header[1:] if line and not line.startswith("#")]
    names = [line[-1] for line in lines]
    ecg_index = next(i for name in ECG_NAMES if name in names for i, n in enumerate(names) if n == name)
    pleth_index = names.index("PLETH")
    raw = loadmat(io.BytesIO(archive.read(f"training/{record}.mat")))["val"]
    if raw.shape != (len(lines), length):
        raise ValueError(f"waveform/header shape mismatch: {record}")
    def physical(i: int) -> np.ndarray:
        # WFDB signal units: physical = (digital - baseline) / gain.
        bits = lines[i][2].split("/")[0]
        gain = float(bits)
        baseline = float(lines[i][4])
        if gain <= 0:
            raise ValueError(f"invalid channel gain: {record}")
        return (raw[i].astype(np.float64) - baseline) / gain
    return physical(ecg_index), physical(pleth_index), rate


def prepare(source: Path, output: Path, seed: int, max_records: int | None = None) -> dict:
    if not source.is_file():
        raise FileNotFoundError(f"Missing {source}; place the original training.zip at this path")
    output.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256()
    with source.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    with ZipFile(source) as archive:
        labels = list(csv.reader(io.StringIO(archive.read("training/ALARMS").decode())))
        eligible = []
        for record, alarm_type, verdict in labels:
            header = archive.read(f"training/{record}.hea").decode().splitlines()
            channels = [line.split()[-1] for line in header[1:] if line and not line.startswith("#")]
            if "PLETH" in channels and any(name in channels for name in ECG_NAMES):
                eligible.append((record, alarm_type, verdict))
        if max_records is not None:
            eligible = eligible[:max_records]
        if len(eligible) < 20:
            raise ValueError("Need at least 20 eligible recordings")
        train, remainder = train_test_split(eligible, test_size=.4, random_state=seed,
                                            stratify=[r[2] for r in eligible])
        validation, test = train_test_split(remainder, test_size=.5, random_state=seed + 1,
                                            stratify=[r[2] for r in remainder])
        splits = {"train": train, "validation": validation, "test": test}
        manifest = []
        rows = []
        for split_name, records in splits.items():
            # Explicit simulated client allocation; whole recordings stay with one client.
            ordered = sorted(records, key=lambda r: hashlib.sha256(f"{seed}:{r[0]}".encode()).hexdigest())
            for pos, (record, alarm_type, verdict) in enumerate(ordered):
                client = pos % 5 if split_name == "train" else None
                manifest.append({"record": record, "split": split_name, "simulated_client": client,
                                 "clinical_alarm_type": alarm_type, "clinical_alarm_true": int(verdict)})
                ecg, pleth, rate = decode(archive, record)
                window = rate * 5
                # A record's first 30s supply only its own causal replay reference.
                history = [pleth[k*window:(k+1)*window] for k in range(6)]
                reference_bank = history_reference(history)
                for index, start in enumerate(range(rate * 30, len(pleth) - window + 1, window)):
                    e, p = ecg[start:start + window], pleth[start:start + window]
                    if not np.isfinite(e).all() or not np.isfinite(p).all():
                        continue
                    base = {"record": record, "split": split_name, "simulated_client": client,
                            "window_start_seconds": start / rate,
                            "clinical_alarm_true_metadata": int(verdict)}
                    # Paired clean/corrupt examples, fixed fault schedule independent of labels.
                    for fault in ("none", FAULTS[1 + index % 4]):
                        altered = inject(p, fault, history[index % 6])
                        features = stats(e, altered)
                        # Observable waveform comparison; computed for every row,
                        # independent of the assigned fault label.
                        finite = np.isfinite(altered)
                        if finite.all():
                            errors = [float(np.mean(np.abs(altered - prior)) /
                                            max(float(np.std(prior)), .01)) for prior in history]
                            features["history_match_error"] = min(errors)
                        else:
                            features["history_match_error"] = 1e6
                        features["history_robust_error"] = robust_history_error(altered, reference_bank)
                        rows.append(base | {"fault": fault, "sensor_fault_label": int(fault != "none")} | features)
        frame = pd.DataFrame(rows)
    if len({r["record"] for r in manifest}) != len(manifest):
        raise AssertionError("record appeared in multiple partitions")
    for split_name in splits:
        part = frame.loc[frame.split == split_name]
        if part.empty or part.sensor_fault_label.nunique() != 2:
            raise ValueError(f"Missing classes in {split_name}")
    frame.to_csv(output / "sensor_windows.csv", index=False)
    pd.DataFrame(manifest).to_csv(output / "record_split_manifest.csv", index=False)
    report = {"source_sha256": digest.hexdigest(), "preparation_version": 3, "seed": seed,
              "split_unit": "recording (patient identities unavailable)",
              "clients": "five simulated training clients assigned by recording",
              "labels": "sensor_fault_label is controlled injection; clinical alarm is unrelated metadata",
              "split_record_counts": {name: len(values) for name, values in splits.items()},
              "split_window_counts": frame.groupby("split").size().to_dict(),
              "fault_counts": frame.fault.value_counts().to_dict(),
              "important_limitations": ["no verified patient-disjoint guarantee", "no real hospital identities",
                                        "faults are synthetic, not observed cyberattacks",
                                        "paired clean/attack rows from the same window must stay within a split"]}
    (output / "preparation_summary.json").write_text(json.dumps(report, indent=2) + "\n")
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--zip", type=Path, default=Path("data/raw/physionet_2015/training.zip"))
    parser.add_argument("--output", type=Path, default=Path("outputs/physionet_2015_prepared_v3"))
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-records", type=int, default=None, help="Small smoke run only; omit for study")
    args = parser.parse_args()
    report = prepare(args.zip, args.output, args.seed, args.max_records)
    print("Record splits:", report["split_record_counts"])
    print("Rows:", report["split_window_counts"])
    print("Saved:", args.output / "preparation_summary.json")


if __name__ == "__main__":
    main()
